import path from "node:path";

// Where tests/auth.setup.ts saves each role's signed-in session cookie, and
// where the rest of the suite reads it back from via
// `test.use({ storageState: ... })`. Gitignored (see e2e/.gitignore) —
// regenerated by the "setup" project on every run.
const authDir = path.resolve(import.meta.dirname, "../.auth");

export const ADMIN_STORAGE_STATE = path.join(authDir, "admin.json");
export const AGENT_STORAGE_STATE = path.join(authDir, "agent.json");
